name: Deploy UI to PCF
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
    
    - name: whatsapp-notify
      id: whatsapp-notify
      env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}
      uses: ishween/whatsapp-push-notify-action@master
        
      
