name: Deploy UI to PCF
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Install Packages
      run: npm install
    
    - name: Build App
      run: npm run build
    
    - name: Pivotal Cloud Foundry (PCF) CLI
      uses: d3sandoval/cloud-foundry-action@1.1.1
      with:
        args: push -f build/manifest.yml -p build
      env:
        CF_TARGET_ORG: goku
        CF_TARGET_SPACE: development
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
    
    - name: Message to Whatsapp
      id: whatsapp-message
      env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_number: ${{ secrets.to_whatsapp_no }}
          from_number: ${{ secrets.from_whatsapp_no }}
          message:  "FbApp - Successfully deployed latest changes. Browse it on http://fbapp.lifecompilers.in/"
      uses: zilurrane/whatsapp-actions@0.0.1
