name: Deploy UI to PCF
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Install Packages
      run: npm install
    
    - name: Build App
      run: npm run build
    
    - name: Pivotal Cloud Foundry (PCF) CLI
      uses: d3sandoval/cloud-foundry-action@1.1.1
