name: Deploy Docker
on:
  push:
    branches:
    - deploy
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build -t ziluli/fbapp .
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: fbapp
        environment_name: Fbapp-env
        version_label: 12345
        region: ap-south-1
        deployment_package: deploy.zip
